language: python

# Python version
python:
  - "3.4"
  - "3.5"
  - "3.6"

# OS(Zesty - Ubuntu 17.04 LTS)와 기타 환경설정을 정의 합니다.
dist: zesty
sudo: required

# 환경변수를 설정합니다.
## matrix 옵션에서 빌드별 장고 버전을 명시했습니다.
env:
  global:
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO_VERSION=1.11.4 DB=sqlite3

# 빌드에 사용될 Dependency를 설정하는 부분입니다.
## 기본적으로 requirments.txt 에 있는 dependency를 설치한 뒤,
## django버전을 빌드별로 설정했습니다.
install:
  - pip install -r requirements.txt

# 빌드 스크립트를 실행하기전에 사용할 명령들입니다.
## mysql에 model_test라는 DB를 만든뒤 migration 파일을 만들도록 했습니다.
before_script:
  - python manage.py makemigrations

# 빌드에 사용할 스크립트입니다.
## 전 migrate와 test가 정상적으로 동작하는 지 확인 할 수 있도록 했습니다.
script:
  - python manage.py migrate -v 3
  - python manage.py test -v 3
