# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_merchandise_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=15, verbose_name='Type')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('date', models.DateField(verbose_name='Transaction Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='merchandise',
            options={'ordering': ['code'], 'verbose_name': 'Merchandise', 'verbose_name_plural': 'Merchandises'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Merchandise'),
        ),
    ]
