# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('inventory', '0004_transaction_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandise',
            options={'ordering': ['category', 'code'], 'verbose_name': 'Merchandise', 'verbose_name_plural': 'Merchandises'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.TransactionData'),
        ),
    ]
