# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 18:05
from __future__ import unicode_literals

from django.db import migrations, models


def set_my_defaults(apps, schema_editor):
    Transaction = apps.get_model('inventory', 'Transaction')
    for trans in Transaction.objects.all():
        trans.prev_quantity = trans.quantity
        trans.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='prev_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prev Quantity'),
        ),
        migrations.RunPython(set_my_defaults),
    ]
