# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('file', models.FileField(upload_to='transaction_data', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Transaction Data',
                'verbose_name_plural': 'Transaction Data',
                'ordering': ['-date'],
            },
        ),
    ]
